addSbtPlugin("com.geirsson"      % "sbt-ci-release" % "1.2.2")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"   % "2.0.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-web"        % "1.4.4")
addSbtPlugin("com.typesafe.play" % "sbt-plugin"     % "2.6.22")
addSbtPlugin("com.typesafe.sbt"  % "sbt-ghpages"    % "0.6.3")
addSbtPlugin("ba.sake"           % "sbt-hepek"      % "0.1.2")
